### ISSUE TITLE
🐛图片导入的问题

### ISSUE THREAD

**Issue by timenb123** [zhulinyv/Semi-Auto-NovelAI-to-Pixiv#95]
### 确认

- 我的版本已更新到最新，且已尝试运行 `pip install -r requirements.txt` 更新依赖库
- 我已查阅[文档-常见问题](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv#readme)，无相关解决方案
- 我已确认[issue](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv/issues)中没有类似的问题或仍然得不到解决

### 环境信息
整合包

### 问题描述（报错）

Traceback (most recent call last):
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\PIL\ImageFile.py", line 204, in load
    seek = self.load_seek
AttributeError: 'PngImageFile' object has no attribute 'load_seek'. Did you mean: 'load_end'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\gradio\blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\src\director_tools.py", line 141, in director_tools_colorize
    json_for_colorize["image"] = img_to_base64(img)
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\utils\imgtools.py", line 63, in img_to_base64
    image.save("./output/temp.png")
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\PIL\Image.py", line 2528, in save
    self._ensure_mutable()
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\PIL\Image.py", line 639, in _ensure_mutable
    self._copy()
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\PIL\Image.py", line 632, in _copy
    self.load()
  File "E:\myfile\data\ai painting\Semi-Auto-NovelAI-to-Pixiv\Python310\lib\site-packages\PIL\ImageFile.py", line 207, in load
    seek = self.fp.seek
AttributeError: 'NoneType' object has no attribute 'seek'

### 复现步骤
无vpn影响，token正常，不管是批量导入还是单独选择图片都会报错，目前尝试了png和jpg两种格式

**Comment by timenb123** [comment]
尝试了只在上色colorize部分有这个问题

**Comment by zhulinyv** [comment]
已修复, 并测试没问题, 请更新

**Comment by timenb123** [comment]
好的

**Comment by timenb123** [comment]
导入问题目前没问题了，但是使用批量生成后只处理了第一张图片，后续就没有了

**Comment by zhulinyv** [comment]
已修复 https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv/commit/bcb3b5c6f841f7fd9bbb1ffcade5a08f6f70b973
